# Generated by Django 4.0 on 2023-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('position', models.CharField(max_length=100)),
                ('hiring_date', models.DateField(default='2021-01-01')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
